apiVersion: apps/v1
kind: Deployment
metadata:
  name: worldtime-starlight-deployment-2
spec:
  selector:
    matchLabels:
      app: worldtime-starlight-2  # Updated to match service selector
  replicas: 1
  template:
    metadata:
      labels:
        app: worldtime-starlight-2  # Updated to match service selector
    spec:
      containers:
        - name: spring-boot-k8s
          image: mustafamirza/worldtime
          imagePullPolicy: Always
          env:
          - name: ORCH_IP
            value: "192.168.103.115"
          - name: ORCH_PORT
            value: "8443"
          - name: PLUGIN_ID
            value: "5eac1074-a374-4abf-9bf4-5fc27dcff683"
          - name: CLIENT_CRDS
            value: "IQ?DPnS7EXDbVxmejWr58S!yb_8FDKxp!Hzb"
          - name: CONN_WEBSOCKET
            value: "true"
          - name: ENABLE_AVOCADO
            value: "true"
          - name: ENABLE_VE
            value: "true"
          - name: LOCAL_DB_FILE
            value: ".avocado.db"
          - name: PARSING_LEVEL
            value: "2"
          - name: VE_DATA-EXPIRY_IN_MINUTES
            value: "1440"
          - name: DEBUG_LOGS
            value: "true"
          - name: AVCD_METADATA_FILENAME
            value: "/metadata1.json"
          - name: AVCD_SERVICE_TAG
            value: WSL-101
          - name: IPC_USING_TCP
            value: "false"
          - name: SLA_PORT
            value: "8901"
          - name: STATS_PORT
            value: "8902"
          - name: POLICY_PORT
            value: "8903"
          - name: LOG_TO_STDOUT
            value: "false"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: worldtime-starlight-samplesvc-2
spec:
  selector:
    app: worldtime-starlight-2
  ports:
    - protocol: "TCP"
      port: 8080
      nodePort: 30008
      targetPort: 8080
  type: NodePort
