apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: worldtime-starlight-meta2-deployment
spec:
  selector:
    matchLabels:
      app: worldtime-starlight-meta2
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: worldtime-starlight-meta2
    spec:
      containers:
        - name: spring-boot-k8s
          image: mustafamirza/worldtime # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          env:
          - name: ORCH_IP
            value: "192.168.103.96"
          - name: ORCH_PORT
            value: "8443"
          - name: PLUGIN_ID
            value: "1f102c17-8369-4c01-b067-63ed9adfab3a"
          - name: CLIENT_PASSWORD
            value: "inrKSOP@M?wJ8CMrWysPB4Km?@5_=_0oWgl?"
          - name: CONN_WEBSOCKET
            value: "true"
          - name: ENABLE_AVOCADO
            value: "true"
          - name: ENABLE_VE
            value: "true"
          - name: LOCAL_DB_FILE
            value: ".avocado.db"
          - name: PARSING_LEVEL
            value: "2"
          - name: VE_DATA-EXPIRY_IN_MINUTES
            value: "1440"
          - name: DEBUG_LOGS
            value: "true"
          - name: AVCD_METADATA_FILENAME
            value: "/metadata2.json"
          - name: AVCD_SERVICE_TAG
            value: worldtime-starlight-meta2
          name: worldtime-debian12-root-web-container
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: worldtime-starlight-meta2-samplesvc
spec:
  selector:
    app: worldtime-starlight-meta2
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      nodePort: 30009 # Fixed Port to access web app
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.
